[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = [ "--mode", "cloudflare", "/web",]

[package]
name = "thibaultleouay/hono-wasmer"
version = "0.1.3"
description = "Hono Website Wasmer starter package"
readme = "README.md"
repository = "https://github.com/openstatusHQ/hono-wasmer"

[dependencies]
"wasmer/winterjs" = "^0.3.4"

[fs]
"/web" = "dist"
